Add doc link to the readme
FluxML/OneHotArrays.jl pull request #14
Opened 2022-07-22 17:38 UTC by mcabbott

2022-07-22 22:14 UTC, darsnack requested changes

2022-07-22 22:14 UTC, darsnack commented on docs/make.jl
> +              assets = ["assets/flux.css"],
I think you need to copy the CSS file over too

2022-07-22 22:22 UTC, mcabbott commented on docs/make.jl
> +              assets = ["assets/flux.css"],
Oh right, somehow I couldn't find it in Optimisers.jl & assumed it was elsewhere on the web server... but now I found it.

2022-08-15 23:47 UTC, darsnack approved these changes

2022-08-15 23:54 UTC, merged