minor doc additions and fixes
FluxML/OneHotArrays.jl pull request #18
Opened 2022-08-01 15:01 UTC by Saransh-cpp

I think `OneHotMatrix` and `OneHotVector` should have their own docstrings as they are present as well as referenced in the manual.

2022-08-01 15:28 UTC, mcabbott approved these changes

2022-08-01 23:30 UTC, darsnack requested changes

2022-08-01 23:30 UTC, darsnack commented on src/array.jl
>  Parameter `I` is the type of the underlying storage, and `T` its eltype.
```suggestion
A one-hot `M`-dimensional array (with `L` labels)
stored as a compact `N`-dimensional array of indices.
Typically constructed by [`onehot`](@ref) and [`onehotbatch`](@ref).
Parameter `I` is the type of the underlying storage, and `T` its eltype.
```

2022-08-01 23:30 UTC, darsnack commented on src/array.jl
> +storage and `L` is the length of labels.
```suggestion
A one-hot vector (with `L` labels) typically constructed using [`onehot`](@ref).
Stored efficiently as a single index of type `T`.
```

2022-08-01 23:30 UTC, darsnack commented on src/array.jl
> +storage, `T` is its eltype and `L` is the length of labels.
```suggestion
A one-hot matrix (with `L` labels) typically constructed using [`onehotbatch`](@ref).
Stored efficiently as a vector of indices with type `I` and eltype `T`.
```

2022-08-01 23:32 UTC, mcabbott commented on src/array.jl
>  Parameter `I` is the type of the underlying storage, and `T` its eltype.
Maybe this should say that `N == M+1` always? And explain that L labels means `size(A,1) == L`?

2022-08-01 23:51 UTC, darsnack commented on src/array.jl
>  Parameter `I` is the type of the underlying storage, and `T` its eltype.
Something like this?

```suggestion
A one-hot `M`-dimensional array (with `L` labels in the first dimension)
stored as a compact `N`-dimensional array of indices (where `N == M + 1`).
Typically constructed by [`onehot`](@ref) and [`onehotbatch`](@ref).
Parameter `I` is the type of the underlying storage, and `T` its eltype.
```

2022-08-02 01:46 UTC, mcabbott commented on src/array.jl
>  Parameter `I` is the type of the underlying storage, and `T` its eltype.
But if you don't know what labels means, I think this is still confusing. Maybe:
```suggestion
A one-hot `M`-dimensional array with `L` labels (i.e. `size(A, 1) == L` and `sum(A, dims=1) == 1`)
stored as a compact `N == M-1`-dimensional array of indices.

Typically constructed by [`onehot`](@ref) and [`onehotbatch`](@ref).
Parameter `I` is the type of the underlying storage, and `T` its eltype.
```
Small details, for sure.

2022-08-02 01:48 UTC, mcabbott commented on src/array.jl
> +storage and `L` is the length of labels.
Maybe this one too could clarify that L is the length, 

```suggestion
A one-hot vector with `L` labels (i.e. `length(A) == L` and `count(A) == 1`) typically constructed by [`onehot`](@ref).
Stored efficiently as a single index of type `T`, usually `UInt32`.
```

2022-08-02 17:23 UTC, Saransh-cpp commented
Thank you for the review, @mcabbott and @darsnack! Updated!

2022-08-15 20:38 UTC, darsnack approved these changes

2022-08-15 20:39 UTC, merged